[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"

[build.env]
PYO3_USE_ABI3_FORWARD_COMPATIBILITY = "1"

[deploy.env]
BOT_TOKEN = "8398207757:AAHqH5mZSwL7rxx6FGZFu-0ZzfIHQ00_I7M"
ADMIN_ID = "8217088275"
PHOTO_URL = "https://www.dropbox.com/scl/fi/w58dqa8v3gypoyx26qgno/photo_2025-09-27_01-31-37-1.jpg?rlkey=s17vgnm63nu209hs7or0zilxr&st=9fejuodz&dl=1"
CRYPTOBOT_TOKEN = "463340:AA7AujJqzBp7kIXfSpxXcGyaQtMXbgk8B4E"
TON_API_KEY = ""